name: Terraform Destroy

on: 
  workflow_dispatch:
    inputs:
        AWS_ACCESS_KEY_ID:
          description: 'AWS Access Key'
          required: false
        AWS_SECRET_ACCESS_KEY:
          description: 'AWS Secret Access Key'
          required: false
        AWS_SESSION_TOKEN:
          description: 'AWS Session Token'
          required: false
        AWS_DEFAULT_REGION:
          description: 'AWS Region'
          required: false
          default: 'us-east-1'
        DEPLOY_ENVIRONMENT:
          description: 'Deployment Environment'
          required: true
          default: 'dev'
        TF_STATE_BUCKET:
          description: 'Terraform State Bucket'
          required: false
          default: 's1sg-tc-terraform-state-bucket-fase5'
        TF_STATE_KEY:
          description: 'Terraform State Key'
          required: false
          default: 'terraform.tfstate'

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ github.event.inputs.AWS_ACCESS_KEY_ID || secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ github.event.inputs.AWS_SECRET_ACCESS_KEY || secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ github.event.inputs.AWS_SESSION_TOKEN || secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ github.event.inputs.AWS_DEFAULT_REGION }}

    - name: Terraform Init
      run: terraform init -backend-config="bucket=${{ github.event.inputs.TF_STATE_BUCKET }}" -backend-config="key=${{ github.event.inputs.TF_STATE_KEY }}" -backend-config="region=${{ github.event.inputs.AWS_DEFAULT_REGION }}"

    - name: Terraform Destroy
      run: terraform destroy -auto-approve
      env:
        TF_VAR_environment: ${{ github.event.inputs.DEPLOY_ENVIRONMENT }}